---
title: 'Linking Github to RStudio'
output: github_document
---

## 1. Initialise your Git installation.

- If you have not been using Git regularly before, initialise your Git installation using the instructions in *Happy Git*,[Chapter 7](https://happygitwithr.com/hello-git.html).

## 2. Clone your Github repository to an R project.

- Follow the directions in *Happy Git*, [Section 16.2](https://happygitwithr.com/existing-github-first.html).
- You can get the repository URL of your Github repository by clicking the green ‘Clone or download’ button from your repository page.
- Be sure to save your R project in a place that you can find it again! You will need to open it every time you want to work on your project in the future (although you can usually also find it in the RStudio File menu under Recent Projects).

## 3. Create README.Rmd.

- From the RStudio File menu, create a new R Markdown file from the Github Document template.
- Use [Github Markdown](https://guides.github.com/features/mastering-markdown/) to edit the home page as you wish.
- Use the Knit button in RStudio to preview how your page will look.

## 4. Push your changes to Github.

- Follow the directions in *Happy Git*, [Sections 16.4 to  16.7](https://happygitwithr.com/existing-github-first.html#stage-and-commit) to stage, commit, and push your changes to Github.
- After several minutes (and possibly several page refreshes), your changes should be visible from the github.io link you made earlier.
